steps:
  - name: "node:10.16.3"
    id: root-install
    entrypoint: npm
    args: ["install"]

  - name: "gcr.io/cloud-builders/gcloud"
    id: fork-build-appointment-search-service
    entrypoint: "bash"
    waitFor:
      - root-install
    args:
      - "-c"
      - |
        gcloud builds submit $d --config=./src/services/appointment-search/cloudbuild.yaml
        wait

  - name: "gcr.io/cloud-builders/gcloud"
    id: fork-build-create-appointment-service
    entrypoint: "bash"
    waitFor:
      - root-install
    args:
      - "-c"
      - |
        gcloud builds submit $d --config=./src/services/create-appointment/cloudbuild.yaml
        wait

  - name: "gcr.io/cloud-builders/gcloud"
    id: fork-build-delete-appointment-service
    entrypoint: "bash"
    waitFor:
      - root-install
    args:
      - "-c"
      - |
        gcloud builds submit $d --config=./src/services/delete-appointment/cloudbuild.yaml
        wait

  - name: "gcr.io/cloud-builders/gcloud"
    id: fork-build-query-appointment-service
    entrypoint: "bash"
    waitFor:
      - root-install
    args:
      - "-c"
      - |
        gcloud builds submit $d --config=./src/services/query-appointment/cloudbuild.yaml
        wait

  - name: "gcr.io/cloud-builders/gcloud"
    id: fork-build-update-appointment-service
    entrypoint: "bash"
    waitFor:
      - root-install
    args:
      - "-c"
      - |
        gcloud builds submit $d --config=./src/services/update-appointment/cloudbuild.yaml
        wait
