steps:
  - name: "node:10.16.3"
    id: root-install
    entrypoint: npm
    args: ["install"]

  - name: "node:10.16.3"
    id: create-appointment-install
    waitFor:
      - root-install
    entrypoint: npm
    args: ["install"]
    dir: src/services/create-appointment

  - name: "node:10.16.3"
    id: delete-appointment-install
    waitFor:
      - root-install
    entrypoint: npm
    args: ["install"]
    dir: src/services/delete-appointment

  - name: "node:10.16.3"
    id: query-appointment-install
    waitFor:
      - root-install
    entrypoint: npm
    args: ["install"]
    dir: src/services/query-appointment

  - name: "node:10.16.3"
    id: update-appointment-install
    waitFor:
      - root-install
    entrypoint: npm
    args: ["install"]
    dir: src/services/update-appointment

  # Validate build
  - name: "node:10.16.3"
    id: lint
    entrypoint: npm
    args: ["run", "lint"]

  - name: "node:10.16.3"
    id: test-unit
    entrypoint: npm
    args: ["run", "test"]

  # Build and push docker image: Create appointment
  - name: "gcr.io/cloud-builders/docker"
    id: create-appointment:0.0.1
    waitFor:
      - test-unit
    args:
      - build
      - --build-arg
      - service=create-appointment
      - -t
      - gcr.io/sweng-581-capstone/create-appointment:0.0.1
      - .

  - name: "gcr.io/cloud-builders/docker"
    id: push-create-appointment
    waitFor:
      - create-appointment:0.0.1
    args: ["push", "gcr.io/sweng-581-capstone/create-appointment:0.0.1"]

  # Build and push docker image: Delete Profile
  - name: "gcr.io/cloud-builders/docker"
    id: delete-appointment:0.0.1
    waitFor:
      - test-unit
    args:
      - build
      - --build-arg
      - service=delete-appointment
      - -t
      - gcr.io/sweng-581-capstone/delete-appointment:0.0.1
      - .

  - name: "gcr.io/cloud-builders/docker"
    id: push-delete-appointment
    waitFor:
      - delete-appointment:0.0.1
    args: ["push", "gcr.io/sweng-581-capstone/delete-appointment:0.0.1"]

  # Build and push docker image: Query Profile
  - name: "gcr.io/cloud-builders/docker"
    id: query-appointment:0.0.1
    waitFor:
      - test-unit
    args:
      - build
      - --build-arg
      - service=query-appointment
      - -t
      - gcr.io/sweng-581-capstone/query-appointment:0.0.1
      - .

  - name: "gcr.io/cloud-builders/docker"
    id: push-query-appointment
    waitFor:
      - query-appointment:0.0.1
    args: ["push", "gcr.io/sweng-581-capstone/query-appointment:0.0.1"]

  # Build and push docker image: Update Profile
  - name: "gcr.io/cloud-builders/docker"
    id: update-appointment:0.0.1
    waitFor:
      - test-unit
    args:
      - build
      - --build-arg
      - service=update-appointment
      - -t
      - gcr.io/sweng-581-capstone/update-appointment:0.0.1
      - .

  - name: "gcr.io/cloud-builders/docker"
    id: push-update-appointment
    waitFor:
      - update-profile:0.0.1
    args: ["push", "gcr.io/sweng-581-capstone/update-appointment:0.0.1"]

  # Deploy to cloud run
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor:
      - push-create-appointment
    args:
      - beta
      - run
      - deploy
      - create-appointment
      - --image=gcr.io/sweng-581-capstone/create-appointment:0.0.1
      - --region=us-central1
      - --platform=managed

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor:
      - push-delete-appointment
    args:
      - beta
      - run
      - deploy
      - delete-appointment
      - --image=gcr.io/sweng-581-capstone/delete-appointment:0.0.1
      - --region=us-central1
      - --platform=managed

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor:
      - push-query-appointment
    args:
      - beta
      - run
      - deploy
      - query-appointment
      - --image=gcr.io/sweng-581-capstone/query-appointment:0.0.1
      - --region=us-central1
      - --platform=managed

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor:
      - push-update-appointment
    args:
      - beta
      - run
      - deploy
      - update-appointment
      - --image=gcr.io/sweng-581-capstone/update-appointment:0.0.1
      - --region=us-central1
      - --platform=managed

images:
  - "gcr.io/sweng-581-capstone/create-appointment:0.0.1"
  - "gcr.io/sweng-581-capstone/delete-appointment:0.0.1"
  - "gcr.io/sweng-581-capstone/query-appointment:0.0.1"
  - "gcr.io/sweng-581-capstone/update-appointment:0.0.1"
